### ISSUE TITLE
Cardplaying example

### ISSUE THREAD

**Issue by Bablooos** [lorserker/ben#161]
Hi, I tried to use Ben as a robot player and it was easy to make a bid or lead, but I didn't understand how to make card playing by Ben. I tried to investigate bot CardPlayer but unsuccessfully. Is it possible to add en example for card playing. Excellent if it could be like CardByCard analysis, but instead of analyze() we can make an play() call returning with recommended card (and other options).
Or maybe example how to properly use a CardPlayer bot.
Cheers

**Comment by ThorvaldAagaard** [comment]
I think you should look in gameapi.py, where there is an api for bid, lead and play (and som other useable functions)

An example

http://ben.aalborgdata.dk:8085/play?user=r2&bn=26&dealer=E&seat=W&vul=@v@V&ctx=--1D--1H--1N--2D--3N------&hand=KJT9.J86.Q9.KQ87&dummy=Q.A943.J863.J952&played=CKC2C4CAC3CQC5CTSKSQS6S2SJD3S7S5STH3S3SAC6C7C9H2CJD2H5C8DJD4D5DQS9H4S8D7D9D6DADTS4H7H8D8HTHK&tournament=mp&details=true

that will return

![Image](https://github.com/user-attachments/assets/ffdb1905-90ee-45b3-a417-1bb2e4f1957d)

But if you send me a board with bidding and play, I can try to make an example for it

**Comment by Bablooos** [comment]
Thank you very much!
Honestly it looks like gameapi is the thing what I am looking for but missed it (based on examples only).
I hope it's completely enough for me.
👍

**Comment by ThorvaldAagaard** [comment]
You should do the following

switch to directory frontend and run
```
python appserver.py
```
then in another prompt from the src directory run
```
python gameserver.py
```
then you can play
but better also start in a third prompt
```
python gameapi.py
```

now go to localhost:8080 and you will have an interface to the API

You can see it in action on my test-server at

http://ben.aalborgdata.dk:8080/

ASK BEN is an interface to the API

**Comment by Bablooos** [comment]
Thanks again. I need gameapi only, I have everything else. One problem exists now - different error messages depending on different version of tensorflow/keras/etc.. And now I'm checking on my and your api: yours is working. 
For example sometimes I have ""An error occurred: 'numpy.ndarray' object has no attribute 'numpy'" message. (TF 2.19, request /bid?bn=26&hand=8qt5k9.8.9.483ak&dealer=N&seat=W&vul=&ctx=1C--1H&verbose=1)
 If I roll back to TF 2.13 then gameapi.py isn't starting with "TypeError: Could not deserialize class 'Functional'...." Ubuntu
So maybe it's reasonal to reproduce your working configuration (running on ben.aalborgdata.dk)

**Comment by ThorvaldAagaard** [comment]
I am using tensorflow 2.18 and haven't tried 2.19.
Keras msut be 3.6 and not 3.7 as they have made a breaking change so models trained with 3.6 does not work in 3.7

So install TF 2.18 and let me know how it goes.

**Comment by Bablooos** [comment]
Installed TF 2.18 and Keras 3.6.0
Loading TensorFlow 2.18.0 - Keras version: 3.6.0
looks like the same as yours

But again see the same error message (

'numpy.ndarray' object has no attribute 'numpy'
File "/home/beetle/ben/src/bots.py", line 980, in bidding_rollout
File "/home/beetle/ben/src/bots.py", line 250, in bid
File "/home/beetle/ben/src/gameapi.py", line 666, in bid

**Comment by ThorvaldAagaard** [comment]
Could be version of numpy

Did you just run 
```
python gameapi.py
```
But show me the entire output I I might be able to tell you what the problem is 
The error often indicates mismatch between models and tensorflow versions

I am using 
numpy                     1.26.4

**Comment by ThorvaldAagaard** [comment]
The request is wrong. It should be

/bid?bn=26&hand=8qt5k9.8.9.483ak&dealer=N&seat=W&vul=&ctx=1C--1H&verbose=1

The query starts with ?

Got this response

{"bid": "1S", "who": "Simulation", "quality": "0.93", "explanation": ""}

**Comment by ThorvaldAagaard** [comment]
This 'numpy.ndarray' object has no attribute 'numpy' is a platform error. It should be fixed in latest version

**Comment by Bablooos** [comment]
Sorry about "bid&". Of course it was "bid?", I just copied wrong to here. And I always check my requests at your server, trying "http://ben.aalborgdata.dk:8085/bid?bn=26&hand=8qt5k9.8.9.483ak&dealer=N&seat=W&vul=&ctx=1C--1H&verbose=1"
I tried different versions of numpy and other software, unsuccessfully.
Unfortunately I am not familiar with Python, so Chat GPT told me that this error message occurs when method "numpy()" is called on a object of a wrong type. I added debug logging into modules and found that
"bot.py: x_bid_np type  <class 'numpy.ndarray'>" (it's my message) so in module bots.py there is a line
                    x_bid_np = x_bid_np.numpy()
where type of x_bid_np is not compatible with "numpy()" call.
In some other place there is a check  "if tf.is_tensor(contracts):" so maybe here this needed to?
I am completely not sure but maybe this is the reason? 
Alex

**Comment by ThorvaldAagaard** [comment]
There was a bug if not running on windows, so just make sure you have latest verseion

Line should just be removed, as the response from the NN is a numpyarray

**Comment by Bablooos** [comment]
Ah, latest version of Ben. I wasted time, you've already fixed it) Now it's working! Thank you) Maybe it could be interesting for you:
---- Your server
http://ben.aalborgdata.dk:8085/bid?bn=26&hand=8qt5k9.8.9.483ak&dealer=N&seat=W&vul=&ctx=1C--1H&verbose=1
{"bid": "1S", "who": "Simulation", "quality": "0.93", "explanation": ""}

---- My server
localhost/bid?bn=26&hand=8qt5k9.8.9.483ak&dealer=N&seat=W&vul=&ctx=1C--1H&verbose=1
{"bid": "2S", "who": "Simulation", "quality": "0.93"}

Requests are completely same )

**Comment by ThorvaldAagaard** [comment]
You can try to add &details=true to get more information, and how the bid is scored

**Comment by Bablooos** [comment]
I am satisfied with any bid at the moment) Just want Ben to work. Just for any case I'll show details of two replies for these request:
bid?bn=26&hand=8qt5k9.8.9.483ak&dealer=N&seat=W&vul=&ctx=1C--1H&verbose=1&details=1


YOUR SERVER
{"bid": "1S", "who": "Simulation", "quality": "0.93", "candidates": [{"call": "1S", "insta_score": 0.75, "adjustment": 1.8, "expected_score": -111, "expected_imp": -0.26, "expected_tricks": 9.6, "alert": "False", "explanation": ""}, {"call": "2S", "insta_score": 0.244, "adjustment": 0.59, "expected_score": -95, "expected_imp": 0.26, "expected_tricks": 9.6}], "samples": ["Axx.Axxx.ATx.Txx Jxxx.Qxx.xxxx.Qx .KJTxx.KQJxx.Jxx KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-2H-3S-4H-4S-X-P-5H-X-P-P-P (10) | 1C-P-1H-2S-P-4S-P-P-X-P-P-P (10)", "Ax.Kxxx.Axx.JTxx xxx.Jxx.QTxx.Qxx Jx.AQTxx.KJxxx.x KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-2H-P-4H-P-P-P (11) | 1C-P-1H-2S-3H-P-4H-P-P-P (11)", "xx.AKxx.Axx.JTxx Jxx.QTxx.JTxxx.x Ax.Jxxx.KQxx.Qxx KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-2H-P-3D-3S-P-P-P (9) | 1C-P-1H-2S-3H-P-4H-P-P-P (8)", "Jxxx.AKQ.Qxx.Jxx xx.Txx.Kxxx.Txxx A.Jxxxxx.AJTxx.Q KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-X-P-4H-P-P-P (12) | 1C-P-1H-2S-P-P-2N-P-3N-P-P-P (11)", "Axx.Qxx.AKx.JTxx Jxx.Jxx.JTxxx.Qx x.AKTxxx.Qxxx.xx KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-X-2S-4H-4S-5H-P-P-P (11) | 1C-P-1H-2S-P-3S-X-P-P-P (10)", "Axxx.K.AJx.QTxxx x.Qxxx.Txxxxx.Jx Jx.AJTxxxx.KQx.x KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-1N-P-3H-P-3N-P-P-P (6) | 1C-P-1H-2S-P-P-4H-P-P-P (10)", "Axx.Kxx.Kxx.Qxxx xx.JTx.QJTxx.Txx Jx.AQxxxx.Axxx.J KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-X-P-4H-P-P-P (10) | 1C-P-1H-2S-P-P-3H-P-3S-P-4H-P-P-P (10)", "AJx.AKx.xxx.QTxx xxx.JTxx.KTxx.Jx x.Qxxxx.AQJxx.xx KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-X-2S-3H-3S-P-P-P (9) | 1C-P-1H-2S-P-3S-P-P-X-P-P-P (9)", "AJx.Kxxx.Axx.Qxx xx.Jxx.xxxx.JTxx xx.AQTxx.KQJTx.x KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-2H-P-4H-P-P-P (12) | 1C-P-1H-2S-P-P-3D-P-4H-P-P-P (12)", "Axx.AKxx.Jx.Qxxx Jxx.JTx.KTxxx.xx x.Qxxxx.AQxxx.JT KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-2H-P-4H-P-P-P (11) | 1C-P-1H-2S-3H-P-4H-P-P-P (11)", "Axx.A.AKTx.QJTxx Jx.JTxxx.xxxx.xx xx.KQxxxx.QJxx.x KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-3D-P-3H-P-3N-P-P-P (8) | 1C-P-1H-2S-3D-P-3H-P-3N-P-P-P (8)", "x.Axxx.AQx.Qxxxx Jxx.JTx.Kxxxx.Tx Axx.KQxxx.JTxx.J KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-2H-P-4H-P-P-P (11) | 1C-P-1H-2S-3H-P-3S-P-3N-P-4H-P-P-P (11)", "Ax.KQ.KJTx.JTxxx xx.Jxxxx.Axxx.xx Jxx.ATxxx.Qxxx.Q KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-2C-P-P-2S-P-P-3H-P-P-P (8) | 1C-P-1H-2S-P-P-P (8)", "Axx.xx.AKx.JTxxx x.JTxxx.JTxxx.Qx Jxx.AKQxx.Qxxx.x KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-P-P-2N-P-3C-P-P-P (5) | 1C-P-1H-2S-P-P-P (8)", "x.AQx.AKxx.QTxxx Axx.JTx.Jxxxx.xx Jxx.Kxxxxx.QTx.J KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-X-2S-4H-4S-5H-X-P-P-P (11) | 1C-P-1H-2S-X-3S-4H-P-P-P (11)", "AJ.x.KQTx.QJxxxx xxx.xxxx.AJxxx.T xx.AKQJTxx.xxx.x KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-2C-P-3H-P-3N-P-P-P (8) | 1C-P-1H-2S-3C-P-4H-P-P-P (9)", "A.Axx.AQTx.QTxxx xxx.Kxxx.xxxx.Jx Jxx.QJTxx.KJxx.x KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-X-2S-3H-3S-4H-P-P-4S-X-P-P-P (7) | 1C-P-1H-2S-X-3S-X-P-P-P (7)", "Ax.QT.KJxx.QJxxx x.xxxxx.Txxx.Txx Jxxx.AKJxx.AQxx. KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-2C-P-3N-P-P-P (10) | 1C-P-1H-2S-P-P-3N-P-P-P (10)", "Axx.QJx.Ax.Qxxxx xxx.xxx.KTxxx.Jx J.AKTxxx.QJxxx.T KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-X-2S-4H-4S-X-P-P-P (9) | 1C-P-1H-2S-P-3S-4H-P-4N-P-5H-P-P-P (11)", "Axx.KJxx.KQx.JTx Jxx.Txx.ATxxx.xx x.AQxxx.Jxxx.Qxx KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-2H-P-2S-3S-4H-4S-P-P-X-P-P-P (11) | 1C-P-1H-2S-P-3S-P-P-P (11)"], "hcp": [12.8, 5.7, 9.2], "shape": [2.5, 3.2, 3.3, 4.1, 2.8, 3.5, 4.2, 2.5, 2.4, 4.9, 3.7, 1.8], "explanation": ""}

MINE
{"bid": "2S", "who": "Simulation", "quality": "0.93", "candidates": [{"call": "2S", "insta_score": 0.244, "adjustment": 0.59, "expected_score": 114, "expected_imp": 3.4, "expected_tricks": 8.9}, {"call": "1S", "insta_score": 0.75, "adjustment": 1.8, "expected_score": -67, "expected_imp": -3.4, "expected_tricks": 9.6}], "samples": ["Axx.Axxx.ATx.Txx Jxxx.Qxx.xxxx.Qx .KJTxx.KQJxx.Jxx KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-2H-3S-4H-4S-P-P-5H-P-P-P (10) | 1C-P-1H-2S-P-4S-X-P-P-P (10)", "Ax.Kxxx.Axx.JTxx xxx.Jxx.QTxx.Qxx Jx.AQTxx.KJxxx.x KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-2H-P-4H-4S-P-P-5H-P-P-P (11) | 1C-P-1H-2S-P-3S-X-P-P-P (9)", "xx.AKxx.Axx.JTxx Jxx.QTxx.JTxxx.x Ax.Jxxx.KQxx.Qxx KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-2H-P-4H-4S-P-P-X-P-P-P (9) | 1C-P-1H-2S-P-3S-X-P-P-P (9)", "Jxxx.AKQ.Qxx.Jxx xx.Txx.Kxxx.Txxx A.Jxxxxx.AJTxx.Q KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-X-P-4H-4S-P-P-5H-P-P-P (12) | 1C-P-1H-2S-P-P-X-P-P-P (7)", "Axx.Qxx.AKx.JTxx Jxx.Jxx.JTxxx.Qx x.AKTxxx.Qxxx.xx KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-X-P-4H-4S-X-P-5H-P-P-P (11) | 1C-P-1H-2S-P-3S-P-P-P (10)", "Axxx.K.AJx.QTxxx x.Qxxx.Txxxxx.Jx Jx.AJTxxxx.KQx.x KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-2C-P-4H-4S-X-P-5H-P-P-P (10) | 1C-P-1H-2S-P-P-5H-P-P-P (10)", "Axx.Kxx.Kxx.Qxxx xx.JTx.QJTxx.Txx Jx.AQxxxx.Axxx.J KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-X-P-4H-4S-P-P-5H-P-P-P (10) | 1C-P-1H-2S-P-P-X-P-P-P (8)", "AJx.AKx.xxx.QTxx xxx.JTxx.KTxx.Jx x.Qxxxx.AQJxx.xx KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-X-P-4H-4S-X-P-5H-P-P-P (10) | 1C-P-1H-2S-P-3S-P-P-P (9)", "AJx.Kxxx.Axx.Qxx xx.Jxx.xxxx.JTxx xx.AQTxx.KQJTx.x KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-2H-P-4H-4S-X-P-5H-P-P-P (12) | 1C-P-1H-2S-P-P-X-P-P-P (8)", "Axx.AKxx.Jx.Qxxx Jxx.JTx.KTxxx.xx x.Qxxxx.AQxxx.JT KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-2H-P-4H-4S-X-P-5H-P-P-P (11) | 1C-P-1H-2S-3H-3S-P-P-P (9)", "Axx.A.AKTx.QJTxx Jx.JTxxx.xxxx.xx xx.KQxxxx.QJxx.x KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-3N-P-4H-4S-X-P-5H-P-P-P (10) | 1C-P-1H-2S-3N-P-P-P (8)", "x.Axxx.AQx.Qxxxx Jxx.JTx.Kxxxx.Tx Axx.KQxxx.JTxx.J KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-2H-P-4H-4S-P-P-5H-P-P-P (11) | 1C-P-1H-2S-P-3S-X-P-P-P (8)", "Ax.KQ.KJTx.JTxxx xx.Jxxxx.Axxx.xx Jxx.ATxxx.Qxxx.Q KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-2C-P-4H-4S-X-P-5H-P-P-P (8) | 1C-P-1H-2S-P-P-P (8)", "Axx.xx.AKx.JTxxx x.JTxxx.JTxxx.Qx Jxx.AKQxx.Qxxx.x KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-P-P-4H-4S-X-P-5H-P-P-P (10) | 1C-P-1H-2S-P-P-X-P-P-P (8)", "x.AQx.AKxx.QTxxx Axx.JTx.Jxxxx.xx Jxx.Kxxxxx.QTx.J KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-X-P-4H-4S-P-P-5H-P-P-P (11) | 1C-P-1H-2S-X-3S-P-P-P (9)", "AJ.x.KQTx.QJxxxx xxx.xxxx.AJxxx.T xx.AKQJTxx.xxx.x KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-2C-P-4H-4S-P-P-5H-P-P-P (9) | 1C-P-1H-2S-3C-4S-5H-P-P-P (9)", "A.Axx.AQTx.QTxxx xxx.Kxxx.xxxx.Jx Jxx.QJTxx.KJxx.x KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-X-P-4H-4S-X-P-P-P (7) | 1C-P-1H-2S-X-3S-P-P-P (7)", "Ax.QT.KJxx.QJxxx x.xxxxx.Txxx.Txx Jxxx.AKJxx.AQxx. KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-2C-P-4N-P-P-P (10) | 1C-P-1H-2S-P-P-X-P-P-P (5)", "Axx.QJx.Ax.Qxxxx xxx.xxx.KTxxx.Jx J.AKTxxx.QJxxx.T KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-X-P-4H-4S-P-P-5H-P-P-P (11) | 1C-P-1H-2S-P-3S-X-P-P-P (9)", "Axx.KJxx.KQx.JTx Jxx.Txx.ATxxx.xx x.AQxxx.Jxxx.Qxx KQTxxx.x.x.AKxxx - 1.00000 | 1C-P-1H-1S-2H-P-4H-4S-X-P-5H-P-P-P (8) | 1C-P-1H-2S-P-3S-P-P-P (11)"], "hcp": [12.8, 5.7, 9.2], "shape": [2.5, 3.2, 3.3, 4.1, 2.8, 3.5, 4.2, 2.5, 2.4, 4.9, 3.7, 1.8]}

**Comment by ThorvaldAagaard** [comment]
Thinking about it, it ise because we are running different platforms, and my server is using Bridge Bidding Analyser for  simulating the bidding, where yours is using a Neural Network.

So it is as expected assuming you are not running windows

**Comment by Ultimatthi** [comment]
It still would be cool to have a minimal working example of a card play (as there is one for bidding and leading)! I cannot quite figure out how to get it working.

**Comment by ThorvaldAagaard** [comment]
Closing due to inactivity
